FROM python:3.10
RUN pip install pandas

# VSコードの拡張「Remote Container」は「Dev Container」に名称変更
# 上記に伴いリモート接続の手順が異なる。
# 左下のマークを押下しF1を押下、Dev Containers Open Folder in ...を選択しディレクトリを選択。
# 終了するときは左下を押下しDev Container→ リモート接続を終了（Close Remote Conaction）を選択